soes_robothand:
  ros__parameters:
    rate_hz: 20.0
    pos_tol_m: 0.01
    settle_s: 0.5

    link_lengths_m: [0.00, 0.17, 0.12, 0.04]

    kp_cart: 1.0
    damping_lambda: 0.1
    qdot_limit_rad_s: [14.0, 14.0, 14.0, 14.0]

    q_min_rad: [-314.16, -157.08, -157.08, -1.5708]
    q_max_rad: [ 314.16,  157.08,  157.08,  1.5708]

    # HOME pose
    q_home_rad: [0.0, 0.0, 0.0, 0.0]
    kp_joint: 1.0
    home_tol_rad: 0.314

    # Spiral parameters
    R0: 0.025
    turns: 3
    alpha: -0.03
    height: 0.04
    omega: 2.0

    # Parameters for slowing down
    far_distance_m: 0.15
    far_home_err_rad: 1.0
    far_speed_scale: 0.7

    # Smoothing factor for velocity transitions
    vel_smooth_alpha: 0.7
