soes_state:
  ros__parameters:

    # ========================
    # --- TIMING PARAMETERS ---
    # ========================
    settle_before_pump_s: 2.0
    order: [0, 1, 2]

    # ========================
    # --- ROLLER PARAMETERS ---
    # ========================
    roller_distance_mm: 70.0
    roller_speed_mm_s: 17.5

    # ==========================
    # --- VISION PARAMETERS ----
    # ==========================
    camera_timeout_s: 5.0

    # ==========================
    # --- TESTING PARAMETERS ----
    # ==========================
    test_period_s: 3.0
    test_amp_rad: [3.14, 3.14, 3.14]
    test_servo_deg: [30.0, 150.0]

    
    # ==========================
    # --- OPTIONAL (for future) -
    # ==========================
    # pump_duty: 1.0      # If you later expose duty cycle control
    # at_target_topic: "/arm/at_target"   # If you add arm feedback


